services:
  ros2-kilted:
    image: ghcr.io/extelligence-ai/bagel/ros2-kilted:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  ros2-jazzy:
    image: ghcr.io/extelligence-ai/bagel/ros2-jazzy:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  ros2-iron:
    image: ghcr.io/extelligence-ai/bagel/ros2-iron:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  ros2-humble:
    image: ghcr.io/extelligence-ai/bagel/ros2-humble:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  ros1-noetic:
    image: ghcr.io/extelligence-ai/bagel/ros1-noetic:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  px4:
    image: ghcr.io/extelligence-ai/bagel/px4:latest

    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  ardupilot:
    image: ghcr.io/extelligence-ai/bagel/ardupilot:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data

  betaflight:
    image: ghcr.io/extelligence-ai/bagel/betaflight:latest
    ports:
      - "${BAGEL_WEBAPP_LOCAL_PORT:-8501}:${BAGEL_WEBAPP_LOCAL_PORT:-8501}"
      - "${BAGEL_MCP_LOCAL_PORT:-8000}:${BAGEL_MCP_LOCAL_PORT:-8000}"
    # volumes:
    #   - <path-to-local-data>:/home/ubuntu/data
