"""Entry point for the Bagel MCP server."""

from typing import Any

import duckdb
from mcp.server.fastmcp import FastMCP
from poml import poml

from settings import settings
from src.reader import factory

server = FastMCP(
    name="Bagel MCP Server",
    host=settings.LOCAL_HOST,
    port=settings.MCP_LOCAL_PORT,
)


@server.tool(title="Read metadata from a robolog.")
def read_metadata(robolog_path: str, configs: dict[str, Any] | None = None) -> dict[str, Any]:
    """Return metadata of the robolog as a dictionary.

    The returned dictionary contains basic information about the robolog in addition
    to the entire metadata dictionary.

    - robolog_id: Unique identifier for the robolog, generated by reading the robolog content.
    - path: Path to the robolog file. Please note that it could be a file or a directory.
    - start_seconds: Start time of the robolog in seconds. Please note that this is not always
        the Unix epoch seconds. For example, it can be the time when the robot started recording.
    - end_seconds: End time of the robolog in seconds. Please note that this is not always
        the Unix epoch seconds. For example, it can be the time when the robot stopped recording.
    - duration_seconds: Duration of the robolog in seconds.
    - size_bytes: Size of the robolog in bytes.
    - total_message_count: Total number of messages in the robolog.
    - topics: List of topics in the robolog.
    - type_names: Mapping of topic names to their message type names.
    - message_counts: Mapping of topic names to their message counts.
    - metadata: The entire metadata dictionary of the robolog. The structure of the metadata will
        vary depending of the robolog type, e.g., ROS1, ROS2, PX4 ULog, etc. This dictionary is
        JSON-serializable and can be used to extract additional information about the robolog.

    Args:
        robolog_path (str): Path to the robolog.
        configs (dict[str, Any] | None): Additional configurations for specific readers.

    Returns:
        dict[str, Any]: A dictionary containing metadata extracted from the robolog.

    """
    reader = factory.make_topic_message_reader(robolog_path, **configs if configs else {})
    return {
        "robolog_id": reader.robolog_id,
        "path": str(reader.path),
        "start_seconds": reader.start_seconds,
        "end_seconds": reader.end_seconds,
        "duration_seconds": reader.duration_seconds,
        "size_bytes": reader.size_bytes,
        "total_message_count": reader.total_message_count,
        "topics": reader.topics,
        "type_names": reader.type_names,
        "message_counts": reader.message_counts,
        "metadata": reader.metadata,
    }


@server.tool(title="Read logging messages from a robolog.")
def read_logging_messages(
    robolog_path: str, configs: dict[str, Any] | None = None
) -> list[dict[str, Any]]:
    """Return logging messages from the robolog as a list of JSON-serializable dictionaries.

    Each dictionary in the list represents a logging message with the following structure:
    - robolog_id: Unique identifier for the robolog, generated by reading the robolog content.
    - timestamp_seconds: Timestamp of the logging message in seconds. Please note that this is
        not always the Unix epoch seconds. For example, it can be the time when the robot logged
        the message.
    - level: Logging level of the message (e.g., DEBUG, INFO, WARN, ERROR).
    - message: The actual logging message content.

    In addition to the above fields, the dictionary may contain additional fields
    depending on the robolog type, e.g., ROS1, ROS2, PX4 ULog, etc. For example, line number,
    function name, and file name, etc.

    Args:
        robolog_path (str): Path to the robolog.
        configs (dict[str, Any] | None): Additional configurations for specific readers.

    Returns:
        list[dict[str, Any]]: A list of dictionaries, each representing a logging message.

    """
    reader = factory.make_topic_message_reader(robolog_path, **configs if configs else {})
    return [msg.to_dict() for msg in reader.logging_messages]


@server.tool(title="Describe the content and structure of each topic in a robolog.")
def describe_topics(
    robolog_path: str, topics: list[str], configs: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Describe the content and structure of each topic in a robolog.

    The description of each topic contains the following keys:
    - "raw_schema": contains original topic IDL (Interface Definition Language) schema.
    - "duckdb_table_name": the name of the DuckDB table corresponding to the topic.
    - "duckdb_table_schema": the schema of the DuckDB table corresponding to the topic.

    Args:
        robolog_path (str): Path to the robolog.
        topics (list[str]): List of topics to describe.
        configs (dict[str, Any] | None): Additional configurations for specific readers.

    Returns:
        dict[str, Any]: A dictionary mapping topic names to their descriptions including DuckDB
            table schema, table name, and the meanings of fields and types.

    """
    reader = factory.make_topic_message_reader(robolog_path, **configs if configs else {})

    def _duckdb_schema(topic: str) -> str:
        dataset = reader.read(topics=[topic], peek=True)
        relation = duckdb.from_arrow(dataset)
        duckdb.register(topic, relation)
        return str(duckdb.query(f'DESCRIBE "{topic}"'))

    return {
        topic: {
            "raw_schema": converter.raw_schema,
            "duckdb_table_name": topic,
            "duckdb_table_schema": _duckdb_schema(topic),
        }
        for topic, converter in reader._converters(topics).items()
    }


@server.tool(title="Query topic messages using a DuckDB SQL query.")
def query_topic_messages(  # noqa: PLR0913
    sql: str,
    robolog_path: str,
    topic: str,
    start_seconds: float | None = None,
    end_seconds: float | None = None,
    configs: dict[str, Any] | None = None,
) -> list[dict[str, Any]]:
    """Query topic messages using DuckDB SQL.

    Args:
        sql (str): The DuckDB SQL query to execute.
        robolog_path (str): Path to the robolog.
        topic (str): The topic name to query.
        start_seconds (float | None, optional): When to start reading messages.
        end_seconds (float | None, optional): When to stop reading messages.
        configs (dict[str, Any] | None): Additional configurations for specific readers.

    Returns:
        list[dict[str, Any]]: A list of dictionaries representing the query results.

    """
    reader = factory.make_topic_message_reader(robolog_path, **configs if configs else {})
    dataset = reader.read(topics=[topic], start_seconds=start_seconds, end_seconds=end_seconds)
    relation = duckdb.from_arrow(dataset)
    duckdb.register(topic, relation)
    result = duckdb.sql(sql)
    return result.to_df().to_dict(orient="records")


@server.tool(title="Answer user's text prompt about the robolog.")
def answer_prompt(robolog_path: str, prompt: str) -> list[dict[str, Any]]:
    """Answer user's text prompt about the robolog.

    Args:
        robolog_path (str): Path to the robolog.
        prompt (str): The user's text prompt.

    Returns:
        list[dict[str, Any]]: The formatted prompt to send to the LLMs.

    """
    return poml(
        "./src/agent/query/messages.poml",
        context={"robolog_path": robolog_path, "prompt": prompt},
    )


@server.tool(title="Calculate the latency of a topic in the robolog.")
def calculate_latency(robolog_path: str, topic: str) -> list[dict[str, Any]]:
    """Calculate the latency of a topic in the robolog.

    Args:
        robolog_path (str): Path to the robolog.
        topic (str): The topic the user is interested in.

    Returns:
        list[dict[str, Any]]: The formatted prompt to send to the LLMs.

    """
    return poml(
        "./src/agent/diagnostics/latency.poml",
        context={"robolog_path": robolog_path, "topic": topic},
    )


if __name__ == "__main__":
    server.run(transport="sse")
