name: Lint Code

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ruff:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml

  hadolint:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile*
          recursive: true
