name: test

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # ROS
          - service: ros2-kilted
          - service: ros2-jazzy
          - service: ros2-iron
          - service: ros2-humble
          - service: ros1-noetic
          - service: ros1-noetic-cv
          # Drones
          - service: px4
          - service: ardupilot
          - service: betaflight
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Free disk space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm
      - name: Build ${{ matrix.service }}
        run: docker compose build ${{ matrix.service }} --build-arg DEV_MODE=true
      - name: Test ${{ matrix.service }}
        run: docker compose run ${{ matrix.service }} uv run pytest -p no:warnings ./test
