name: test

on:
  pull_request:
    branches:
      - stage
    types:
      - opened
      - synchronize
      - reopened

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # ROS
          - service: ros2-kilted
          - service: ros2-jazzy
          - service: ros2-iron
          - service: ros2-humble
          - service: ros1-noetic
          # Drones
          - service: px4
          - service: ardupilot
          - service: betaflight
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and test ${{ matrix.service }}
        run: |
          # Build the image
          docker compose build ${{ matrix.service }} --build-arg DEV_MODE=true

          # Run unit tests
          docker compose run ${{ matrix.service }} uv run pytest -p no:warnings ./test
